Repository NubeIO/rubix-point-server, pull requests merged in 2020-12, with the labels that each got.

#134 mqtt multiple clients
  logging/logging.conf
  settings/config.example.ini
  src/__init__.py
  src/background.py
  src/ini_config.py
  src/services/mqtt_client/mqtt_client.py
Labels: ready for review

#135 Add math function and do calculations
  src/event_dispatcher.py
  src/interfaces/point.py
  src/models/point/model_point.py
  src/models/point/model_point_store.py
  src/models/point/model_point_store_history.py
  src/resources/rest_schema/schema_point.py
  src/services/histories/sync/influxdb.py
  src/services/mqtt_client/mqtt_client.py
  src/source_drivers/modbus/models/device.py
  src/source_drivers/modbus/models/network.py
  src/source_drivers/modbus/models/point.py
  src/source_drivers/modbus/resources/point/point_base.py
  src/source_drivers/modbus/resources/point/point_singular.py
  src/source_drivers/modbus/resources/rest_schema/schema_modbus_device.py
  src/source_drivers/modbus/resources/rest_schema/schema_modbus_network.py
  src/source_drivers/modbus/resources/rest_schema/schema_modbus_point.py
  src/source_drivers/modbus/services/__init__.py
  src/source_drivers/modbus/services/modbus_functions/polling/poll.py
  src/source_drivers/modbus/services/rtu_polling.py
  src/source_drivers/modbus/services/tcp_polling.py
Labels: WIP

#141 Fix breaking issue of /system/ping
  src/background.py
  src/services/mqtt_client/mqtt_client.py
  src/system/resources/ping.py
Labels: ready for review

#139 rework modbus polling
  logging/logging.conf
  src/background.py
  src/event_dispatcher.py
  src/loggers.py
  src/models/device/model_device.py
  src/models/model_base.py
  src/models/network/model_network.py
  src/models/point/model_point.py
  src/routes.py
  src/services/event_service_base.py
  src/source_drivers/modbus/models/device.py
  src/source_drivers/modbus/models/network.py
  src/source_drivers/modbus/models/point.py
  src/source_drivers/modbus/resources/point/point_singular.py
  src/source_drivers/modbus/resources/rest_schema/schema_modbus_device.py
  src/source_drivers/modbus/resources/rest_schema/schema_modbus_point.py
  src/source_drivers/modbus/services/__init__.py
  src/source_drivers/modbus/services/modbus_functions/function_utils.py
  src/source_drivers/modbus/services/modbus_functions/polling/functions.py
  src/source_drivers/modbus/services/modbus_functions/polling/poll.py
  src/source_drivers/modbus/services/modbus_functions/polling/poll_funcs.py
  src/source_drivers/modbus/services/modbus_polling.py
  src/source_drivers/modbus/services/rtu_polling.py
  src/source_drivers/modbus/services/tcp_polling.py
  tests/rest/req_modbus_rtu.py
Labels: ready for review

#148 fix write single register
  src/source_drivers/modbus/services/modbus_functions/function_utils.py
  src/source_drivers/modbus/services/modbus_functions/polling/functions.py
Labels: ready for review

#150 fix setting ping_point to null
  src/source_drivers/modbus/models/device.py
Labels: ready for review

#152 Implement Generic Point
  .gitignore
  logging/logging.example.conf
  settings/config.example.ini
  src/__init__.py
  src/background.py
  src/event_dispatcher.py
  src/ini_config.py
  src/models/device/model_device.py
  src/models/model_base.py
  src/models/network/model_network.py
  src/models/point/model_point.py
  src/models/point/model_point_store.py
  src/models/point/model_point_store_history.py
  src/resources/resource_device.py
  src/resources/resource_point.py
  src/routes.py
  src/services/event_service_base.py
  src/services/histories/history_local.py
  src/services/mqtt_client/mqtt_client.py
  src/services/mqtt_client/mqtt_client_base.py
  src/source_drivers/generic/__init__.py
  src/source_drivers/generic/models/__init__.py
  src/source_drivers/generic/models/device.py
  src/source_drivers/generic/models/network.py
  src/source_drivers/generic/models/point.py
  src/source_drivers/generic/resources/__init__.py
  src/source_drivers/generic/resources/device/__init__.py
  src/source_drivers/generic/resources/device/device_base.py
  src/source_drivers/generic/resources/device/device_plural.py
  src/source_drivers/generic/resources/device/device_singular.py
  src/source_drivers/generic/resources/network/__init__.py
  src/source_drivers/generic/resources/network/network_base.py
  src/source_drivers/generic/resources/network/network_plural.py
  src/source_drivers/generic/resources/network/network_singular.py
  src/source_drivers/generic/resources/point/__init__.py
  src/source_drivers/generic/resources/point/point_base.py
  src/source_drivers/generic/resources/point/point_plural.py
  src/source_drivers/generic/resources/point/point_singular.py
  src/source_drivers/generic/resources/rest_schema/__init__.py
  src/source_drivers/generic/resources/rest_schema/schema_generic_device.py
  src/source_drivers/generic/resources/rest_schema/schema_generic_network.py
  src/source_drivers/generic/resources/rest_schema/schema_generic_point.py
  src/source_drivers/generic/services/__init__.py
  src/source_drivers/generic/services/generic_point_listener.py
  src/source_drivers/modbus/services/modbus_functions/polling/poll.py
  src/system/resources/ping.py
Labels: core, driver, ready for review

#153 Improvement/endpoints
  src/resources/resource_device.py
  src/resources/resource_network.py
  src/resources/rest_schema/schema_device.py
  src/resources/rest_schema/schema_network.py
  src/resources/utils.py
  src/source_drivers/generic/resources/device/device_base.py
  src/source_drivers/generic/resources/device/device_plural.py
  src/source_drivers/generic/resources/device/device_singular.py
  src/source_drivers/generic/resources/network/network_base.py
  src/source_drivers/generic/resources/network/network_plural.py
  src/source_drivers/generic/resources/network/network_singular.py
  src/source_drivers/generic/resources/rest_schema/schema_generic_device.py
  src/source_drivers/generic/resources/rest_schema/schema_generic_network.py
  src/source_drivers/modbus/resources/device/device_base.py
  src/source_drivers/modbus/resources/device/device_plural.py
  src/source_drivers/modbus/resources/device/device_singular.py
  src/source_drivers/modbus/resources/network/network_base.py
  src/source_drivers/modbus/resources/network/network_plural.py
  src/source_drivers/modbus/resources/network/network_singular.py
  src/source_drivers/modbus/resources/rest_schema/schema_modbus_device.py
  src/source_drivers/modbus/resources/rest_schema/schema_modbus_network.py
Labels: ready for review

#166 remove bacnet code
  poetry.lock
  pyproject.toml
  src/routes.py
  src/source_drivers/bacnet/__init__.py
  src/source_drivers/bacnet/interfaces/__init__.py
  src/source_drivers/bacnet/interfaces/points.py
  src/source_drivers/bacnet/models/__init__.py
  src/source_drivers/bacnet/models/device.py
  src/source_drivers/bacnet/models/network.py
  src/source_drivers/bacnet/resources/__init__.py
  src/source_drivers/bacnet/resources/device.py
  src/source_drivers/bacnet/resources/fields.py
  src/source_drivers/bacnet/resources/network.py
  src/source_drivers/bacnet/services/__init__.py
  src/source_drivers/bacnet/services/device.py
  src/source_drivers/bacnet/services/network.py
  tests/bacnet/bac0/bac0-logging.py
  tests/bacnet/bac0/bac0_points.py
  tests/bacnet/bac0/bac0_read.py
  tests/bacnet/bac0/bac0_write_prop.py
  tests/bacnet/bac0/device_properties.py
  tests/bacnet/bac0/device_test_settings.py
  tests/bacnet/bac0/flask-rest-example.py
  tests/bacnet/bac0/loop-read.py
  tests/bacnet/bac0/test-bacnet-server.py
  tests/bacnet/bac0_server_2/bacnet_device.py
  tests/bacnet/bac0_server_2/main.py
  tests/bacnet/misc/BACpypes.ini
  tests/bacnet/misc/bacnet-server.py
  tests/bacnet/misc/commons.py
  tests/bacnet/misc/example-1.py
  tests/bacnet/misc/working-example-no-errors.py
Labels: ready for review
